logo2brand = {
    'Agnes b/Agnes b1': 'Agnes b',
    'Agnes_b/Agnes_b1': 'Agnes b',
    'Agnes_b/Agnes_b2': 'Agnes b',
    'Agnes_b/Agnes_b3': 'Agnes b',
    'Agnes_b/Agnes_b4': 'Agnes b',
    'Aston_Martin/Aston_Martin1': 'Aston Martin',
    'Boy_London/Boy_London1': 'Boy London',
    'Boy_London/Boy_London2': 'Boy London',
    'burberry/burberry1': 'Burberry',
    'burberry/burberry2': 'Burberry',
    'Burberry/Burberry1': 'Burberry',
    'Burberry/Burberry2': 'Burberry',
    'Burberry/Burberry3': 'Burberry',
    'Cartier/Cartier3': 'Cartier',
    'cartier/cartier1': 'Cartier',
    'cartier/cartier3': 'Cartier',
    'Estee_Lauder/Estee_Lauder2': 'Estee Lauder',
    'Estee Lauder/Estee Lauder1': 'Estee Lauder',
    'Estee Lauder/Estee Lauder2': 'Estee Lauder',
    'hello_kitty/hello_kitty1': 'Hello Kitty',
    'hello_kitty/hello_kitty2': 'Hello Kitty',
    'Issey_Miyake/Issey_Miyake2': 'Issey Miyake',
    'KYLIE/KYLIE1': 'KYLIE',
    'KYLIE/KYLIE2': 'KYLIE',
    'KYLIE/KYLIE3': 'KYLIE',
    'Mickey_Mouse/Mickey_Mouse1': 'Mickey Mouse',
    'nike/nike1': 'Nike',
    'nike/nike2': 'Nike',
    'nike/nike5': 'Nike',
    'nike/nike15': 'Nike',
    'Pokemon/Pokemon1': 'Pokemon',
    'SENNHEISER/SENNHEISER1': 'Sennheiser',
    'snow_white/snow_white1': 'Snow White',
    'tresor_paris/tresor_paris1': 'Tresor Paris',
    'tresor_paris/tresor_paris2': 'Tresor Paris',
    'Versace/Versace1': 'Versace',
    'Versace/Versace2': 'Versace',
    'Versace/Versace3': 'Versace',
    'Versace/Versace4': 'Versace',
    'Versace/Versace7': 'Versace',
    'xtep/xtep1': 'Xtep',
    'bally/bally1': 'Bally',
    'TENNESSEE TITANS/TENNESSEE TITANS1': 'Tennessee Titans',
    'chrome_hearts/chrome_hearts2': 'Chrome Hearts',
    'chrome_hearts/chrome_hearts4': 'Chrome Hearts',
    'chrome_hearts/chrome_hearts5': 'Chrome Hearts',
    'Dior/Dior1': 'Dior',
    'Dior/Dior2': 'Dior',
    'POWER WHEELS/POWER WHEELS1': 'Power Wheels',
    'Thom Browne/Thom Browne1': 'Thom Browne',
    'Thom Browne/Thom Browne2': 'Thom Browne',
    'The Hunger Games/The Hunger Games1': 'The Hunger Games',
    'FIREMAN SAM/FIREMAN SAM1': 'Fireman Sam',
    'bostitch/bostitch1': 'Bostitch',
    'Philipp Plein/Philipp Plein1': 'Philipp Plein',
    'levis/levis2': 'Levis',
    'levis/levis6': 'Levis',
    'levis/levis11': 'Levis',
    'conair/conair1': 'Conair',
    'Conair/Conair1': 'Conair',
    'Van_Cleef/Van_Cleef1': 'Van Cleef',
    'Van_Cleef/Van_Cleef2': 'Van Cleef',
    'Van_Cleef/Van_Cleef3': 'Van Cleef',
    'LOS ANGELES CHARGERS/LOS ANGELES CHARGERS1': 'Los Angeles Chargers',
    'piaget/piaget1': 'Piaget',
    'Volvo/Volvo1': 'Volvo',
    'VOLCOM/VOLCOM1': 'Volvo',
    'David_Yurman/David_Yurman1': 'David Yurman',
    'David_Yurman/David Yurman2': 'David Yurman',
    'David_Yurman/David_Yurman2': 'David Yurman',
    'AQUABEADS/AQUABEADS1': 'Aquabeads',
    'fox/fox1': 'Fox',
    'fox/fox2': 'Fox',
    'subaru/subaru1': 'Subaru',
    'subaru1': 'Subaru',
    'toyota/toyota1': 'Toyota',
    'toyota1': 'Toyota'
}

sample_logo = [
    'Agnes_b/Agnes_b1',
    'Aston_Martin/Aston_Martin1',
    'Boy_London/Boy_London1',
    'burberry/burberry1',
    'burberry/burberry2',
    'Cartier/Cartier3',
    'Estee_Lauder/Estee_Lauder2',
    'hello_kitty/hello_kitty1',
    'Issey_Miyake/Issey_Miyake2',
    'KYLIE/KYLIE3',
    'Mickey_Mouse/Mickey_Mouse1',
    'nike/nike1',
    'Pokemon/Pokemon1',
    'SENNHEISER/SENNHEISER1',
    'snow_white/snow_white1',
    'tresor_paris/tresor_paris1',
    'Versace/Versace3',
    'Versace/Versace4',
    'xtep/xtep1',
    'bally/bally1'
]
# 训练集2添加的类别
sample_logo2 = [
    'TENNESSEE TITANS/TENNESSEE TITANS1',
    'chrome_hearts/chrome_hearts2',
    'Dior/Dior1',
    'POWER WHEELS/POWER WHEELS1',
    'Thom Browne/Thom Browne1',
    'The Hunger Games/The Hunger Games1',
    'FIREMAN SAM/FIREMAN SAM1',
    'bostitch/bostitch1',
    'Philipp Plein/Philipp Plein1',
    'levis/levis2',
    'conair/conair1',
    'Van_Cleef/Van_Cleef1',
    'LOS ANGELES CHARGERS/LOS ANGELES CHARGERS1',
    'piaget/piaget1',
    'Volvo/Volvo1',
    'David_Yurman/David Yurman2',
    'AQUABEADS/AQUABEADS1',
    'fox/fox2',
    'subaru/subaru1',
    'toyota/toyota1'
]

test_logo = [
    'new_balance/new_balance1-186',
    'hermes/hermes6-102',
    'puma/puma3-141',
    'Comme Des Garcons/Comme Des Garcons1',
    'Metallica/Metallica1',
    'FISHER-PRICE/FISHER-PRICE1',
    'lululemon/lululemon1-237',
    'Mont_blanc/Mont_blanc1-111',
    'Walt_Disney/Walt_disney15',
    'ARIZONA CARDINALS/ARIZONA CARDINALS1',
    'REVLON/REVLON2',
    'smurf/SMURF1',
    'OAKLAND RAIDERS/OAKLAND RAIDERS1',
    'Tesla/Tesla1',
    'dc_shoes/DC_Shoes1',
    'redbull/redbull1',
    # 'Estee_Lauder/Estee_Lauder4-300',
    'puma/puma1-149',
    # 'Dior/dior2-110',
    'BUFFALO BILLS/BUFFALO BILLS1',
    'LOS ANGELES LAKERS/LOS ANGELES LAKERS1']


brand_link = {
    'dc_shoes': ['dc', ]
}
