logo2brand_org = {
    '20th_century_fox/20th_century_fox1': '20th Century Fox',
    'abercrombie&fitch/Abercrombie&fitch1-174': 'Abercrombie & Fitch',
    'abercrombie&fitch/Abercrombie&fitch2-39': 'Abercrombie & Fitch',
    'abercrombie&fitch/Abercrombie&fitch5-204': 'Abercrombie & Fitch',
    'Abercrombie&fitch/Abercrombie&fitch1': 'Abercrombie & Fitch',
    'Abercrombie&fitch/Abercrombie&fitch2': 'Abercrombie & Fitch',
    'Abercrombie&fitch/Abercrombie&fitch5': 'Abercrombie & Fitch',
    'ABT/ABT1': 'ABT',
    'ABT/ABT': 'ABT',
    'Adidas/Adidas2': 'Adidas',
    'Adidas/Adidas3': 'Adidas',
    'Adidas/Adidas4': 'Adidas',
    'Adidas/Adidas5': 'Adidas',
    'Aesthetic Revolution/Aesthetic Revolution1': 'Aesthetic Revolution',
    'Aesthetic Revolution': 'Aesthetic Revolution',
    'Agnes_b/Agnes_b1': 'Agnes b',
    'Agnes_b/Agnes_b2-236': 'Agnes b',
    'Agnes_b/Agnes_b3-5': 'Agnes b',
    'Agnes_b/Agnes_b4-291': 'Agnes b',
    'aibo/aibo1': 'Aibo',
    'AIBO/AIBO1': 'Aibo',
    'AIR_HOGUS/AIR_HOGUS1': 'Air Hogus',
    'AIR_HOGUS/AIR_HOGUS2': 'Air Hogus',
    'ALMAY/ALMAY1': 'Almay',
    'Alphalete/Alphalete1': 'Alphalete',
    'AMERICAN GIRL/AMERICAN GIRL1': 'American Girl',
    'anne klein/anne klein2-233': 'Anne Klein',
    'AQUABEADS/AQUABEADS1': 'Aquabeads',
    'ARIZONA CARDINALS/ARIZONA CARDINALS1': 'Arizona Cardinals',
    'ARIZONA CARDINAL/ARIZONA CARDINAL1': 'Arizona Cardinals',
    'arnette/arnette1': 'Arnette',
    'arnette/arnette2': 'Arnette',
    'ASSOS/ASSOS1': 'Assos',
    'Aston_Martin/Aston_Martin1': 'Aston Martin',
    'automobili lamborghini/AUTOMOBILI LAMBORGHINI1': 'Lamborghini',
    'automobili lamborghini/automobili lamborghini1': 'Lamborghini',
    'Baby Annabell/Baby Annabell1': 'Baby Annabell',
    'Balenciaga/Balenciaga1-183': 'Balenciaga',
    'Balenciaga/Balenciaga2-115': 'Balenciaga',
    'bally/bally1': 'Bally',
    'BALTIMORE RAVENS/BALTIMORE RAVENS1': 'Baltimore Ravens',
    'baume&mercier/baume&mercier1-113': 'Baume & Mercier',
    'baume&mercier/baume&mercier2-172': 'Baume & Mercier',
    'BCBG/BCBG1': 'BCBG',
    'BCBG/BCBG': 'BCBG',
    'benz/benz1': 'Benz',
    'BIC/BIC1': 'BIC',
    'BIC': 'BIC',
    'birkenstock/birkenstock1': 'Birkenstock',
    'Blizzard/Blizzard1': 'Blizzard',
    'Blizzard/Blizzard3': 'Blizzard',
    'Blizzard3ww': 'Blizzard',
    'Blokus/Blokus1': 'Blokus',
    'Blokus/Blokus1w': 'Blokus',
    'blumarine/blumarine': 'Blumarine',
    'blumarine/blumarine1': 'Blumarine',
    'blumarine/blumarine2': 'Blumarine',
    'BOB THE BUILDER/BOB THE BUILDER1': 'Bob The Builder',
    'BOBBI BROWN/BOBBI BROWN1': 'Bobbi Brown',
    'Body_Beast/Body_Beast1': 'Body Beast',
    'body_beast/body_beast1': 'Body Beast',
    'borgward/borgward1': 'Borgward',
    'borgward1': 'Borgward',
    'bose/bose1': 'Bose',
    'bostitch/bostitch1': 'Bostitch',
    'Bottega_veneta/bottega_veneta2': 'Bottega Veneta',
    'Bottega_veneta/bottega_veneta3': 'Bottega Veneta',
    'Boy_London/Boy_London1': 'Boy London',
    'Boy_London/Boy_London2': 'Boy London',
    'BRONCOS/BRONCOS1': 'Broncos',
    'BUFFALO BILLS/BUFFALO BILLS1': 'Buffalo Bills',
    'BUFFALO BILLS/BUFFALO BILLS1ww': 'Buffalo Bills',
    'BULTACO CEMOTO/BULTACO CEMOTO1': 'Bultaco Cemoto',
    'bunchems/Bunchems1': 'Bunchems',
    'Bunchems/Bunchems1': 'Bunchems',
    'Burberry/Burberry1': 'Burberry',
    'Burberry/Burberry2': 'Burberry',
    'burberry/burberry1': 'Burberry',
    'burberry/burberry2': 'Burberry',
    'burberry/burberry3-97': 'Burberry',
    'Burberry/Burberry3': 'Burberry',
    'Bvlgari/Bvlgari1-50': 'Bvlgari',
    'Bvlgari/Bvlgari2-105': 'Bvlgari',
    'Bvlgari/Bvlgari3-259': 'Bvlgari',
    'cadillac/Cadillac1': 'Cadillac',
    'cadillac/cadillac1': 'Cadillac',
    'calvin_klein/calvin_klein1': 'Calvin Klein',
    'calvin_klein/calvin_klein2': 'Calvin Klein',
    'CAMPER/camper1': 'Camper',
    'camper/camper1': 'Camper',
    'Carlsson/Carlsson1': 'Carlsson',
    'CAROLINA PANTHERS/CAROLINA PANTHERS1': 'Carolina Panthers',
    'CAROLINA PANTHERS/CAROLINA PANTHERS1w': 'Carolina Panthers',
    'Cartier/Cartier1-144': 'Cartier',
    'Cartier/Cartier2-160': 'Cartier',
    'cartier/cartier1': 'Cartier',
    'cartier/cartier2': 'Cartier',
    'Cartier/Cartier3': 'Cartier',
    'Cartier/Cartier4': 'Cartier',
    'Celine/Celine1-66': 'Celine',
    'Celine/Celine2-198': 'Celine',
    'Celine/Celine3-167': 'Celine',
    'cfmartin&co/CFMARTIN&CO1': 'Cfmartin & Co',
    'CFMARTIN&CO/CFMARTIN&CO1': 'Cfmartin & Co',
    'champion/champion1-44': 'Champion',
    'champion/champion2-145': 'Champion',
    'Chanel/Chanel1': 'Chanel',
    'Chanel/Chanel2': 'Chanel',
    'Chanel/Chanel3-197': 'Chanel',
    'Chanel/Chanel4-300': 'Chanel',
    'Chanel/Chanel5-300': 'Chanel',
    'chevrolet/chevrolet1': 'Chevrolet',
    'CHICAGO BEARS/CHICAGO BEARS1': 'Chicago Bears',
    'CHICAGO BEARS/CHICAGO BEARS2': 'Chicago Bears',
    'CHICAGO BULLS/CHICAGO BULLS1': 'Chicago Bulls',
    'chloe/chloe1': 'Chloe',
    'chrome_hearts/chrome_hearts1-84': 'Chrome Hearts',
    'chrome_hearts/chrome_hearts2': 'Chrome Hearts',
    'chrome_hearts/chrome_hearts3-172': 'Chrome Hearts',
    'chrome_hearts/chrome_hearts4-220': 'Chrome Hearts',
    'chrome_hearts/chrome_hearts5-205': 'Chrome Hearts',
    'CINCINNATI BENGALS/CINCINNATI BENGALS1': 'Cincinnati Bengals',
    'CINCINNATI BENGALS/CINCINNATI BENGALS2': 'Cincinnati Bengals',
    'CINCINNATI BENGALS1': 'CINCINNATI BENGALS',
    'CLEVELAND BROWNS/CLEVELAND BROWNS1': 'Cleveland Browns',
    'CLEVELAND BROWNS/CLEVELAND BROWNS2': 'Cleveland Browns',
    'coach/coach2-125': 'Coach',
    'coach/coach3-143': 'Coach',
    'cocoon/COCOON1': 'Cocoon',
    'COCOON/COCOON1': 'Cocoon',
    'columbia/columbia1': 'Columbia',
    'COLUMBIA/columbia1-211': 'Columbia',
    'Comme Des Garcons/Comme Des Garcons1': 'Comme Des Garcons',
    'Conair/Conair1': 'Conair',
    'converse/converse2-104': 'Converse',
    'copper fit/copper fit1': 'Copper Fit',
    'CRAZY AARON/CRAZY AARON1': 'Crazy Aaron',
    "CRAZY AARON'S/CRAZY AARON'S1": 'Crazy Aaron',
    'DALLAS COWBOYS/DALLAS COWBOYS1': 'Dallas Cowboys',
    'darth_vader/Darth_Vader1': 'Darth Vader',
    'David_Yurman/David_Yurman2': 'David Yurman',
    'David_Yurman/David_Yurman1-52': 'David Yurman',
    'dc_shoes/DC_Shoes1': 'DC',
    'DC_Shoes/DC_Shoes1': 'DC',
    'DETROIT LIONS/DETROIT LIONS1': 'Detroit Lions',
    'Dewalt/Dewalt1': 'Dewalt',
    'Dior/Dior1': 'Dior',
    'Dior/dior2-110': 'Dior',
    'Dior/Dior2': 'Dior',
    'Dior/Dior3-300': 'Dior',
    'Dior/Dior4-4': 'Dior',
    'Dior/Dior5-164': 'Dior',
    'Dior/Dior5': 'Dior',
    'DKNY/DKNY3': 'Dkny',
    'Donald_Duck/Donald_Duck1': 'Donald Duck',
    'donna_karan/donna_karan1': 'DKNY',
    'donna_karan/donna_karan2': 'DKNY',
    'dr martens/dr martens2': 'Dr Martens',
    'Dr Martens/Dr Martens1': 'Dr Martens',
    'dunhill/dunhill1-277': 'Dunhill',
    'dunhill/dunhill2': 'Dunhill',
    'E-head/E-head1': 'E-Head',
    'Ecko unltd/Ecko unltd1': 'Ecko Unltd',
    'ELF ON THE SHELF/ELF ON THE SHELF1-131': 'Elf On The Shelf',
    'ELF ON THE SHELF/ELF ON THE SHELF2-186': 'Elf On The Shelf',
    'ELF ON THE SHELF/ELF ON THE SHELF3-289': 'Elf On The Shelf',
    'ELF ON THE SHELF/ELF ON THE SHELF4': 'Elf On The Shelf',
    'ELF ON THE SHELF/ELF ON THE SHELF4-292': 'Elf On The Shelf',
    'ELF ON THE SHELF/ELF ON THE SHELF5-拉框300-161找图': 'Elf On The Shelf',
    'ELF ON THE SHELF/ELF ON THE SHELF5': 'Elf On The Shelf',
    'essilor/essilor1-39': 'Essilor',
    'essilor/essilor2-234': 'Essilor',
    'Estee_Lauder/Estee_Lauder1': 'Estee Lauder',
    'Estee_Lauder/Estee_Lauder2': 'Estee Lauder',
    'Estee_Lauder/Estee_Lauder3-240': 'Estee Lauder',
    'Estee_Lauder/Estee_Lauder4-300': 'Estee Lauder',
    'FENDI/fendi1-42': 'Fendi',
    'FENDI/fendi2-294': 'Fendi',

    'FENDI/fendi3-136': 'Fendi',
    'FENDI/fendi6-300': 'Fendi',
    'FENDI/fendi7-184': 'Fendi',
    'FENDI/fendi8-220': 'Fendi',
    'fendi/fendi1-42': 'Fendi',
    'fendi/fendi2-294': 'Fendi',
    'fendi/fendi3-136': 'Fendi',
    'fendi/fendi6-300': 'Fendi',
    'fendi/fendi7-184': 'Fendi',
    'fendi/fendi8-220': 'Fendi',
    'fila/fila1': 'Fila',
    'fingerlings/Fingerlings1': 'Fingerlings',
    'FIREMAN SAM/FIREMAN SAM1': 'Fireman Sam',
    'FISHER-PRICE/FISHER-PRICE1': 'Fisher-Price',
    'fox/fox1-146': 'Fox',
    'fox/fox2': 'Fox',
    'Furla/Furla1-100': 'Furla',
    'Furla/Furla2-300-252': 'Furla',
    'Furla/Furla2-33': 'Furla',
    'general_motors/General Motors1': 'General Motors',
    'general_motors/general_motors1': 'General Motors',
    'givenchy/givenchy2-164': 'Givenchy',
    'givenchy/givenchy3-107': 'Givenchy',
    'GOLD S GYM/GOLD S GYM1': 'Gold S Gym',
    'GOLD S GYM/GOLD S GYM2': 'Gold S Gym',
    'goyard/goyard1': 'Goyard',
    'goyard/goyard2': 'Goyard',
    'goyard/GOYARD1-117': 'Goyard',
    'goyard/GOYARD2-154': 'Goyard',
    'GOYARD/GOYARD1': 'Goyard',
    'GOYARD/GOYARD2-154': 'Goyard',
    'goyard/goyard3-197': 'Goyard',
    'GREEN BAY PACKERS/GREEN BAY PACKERS1': 'Green Bay Packers',
    'Gucci/gucci1-222': 'Gucci',
    'Gucci/gucci1': 'Gucci',
    'Gucci/gucci2': 'Gucci',
    'Gucci/gucci3': 'Gucci',
    'Gucci/gucci4': 'Gucci',
    'Gucci/gucci12': 'Gucci',
    'Gucci/gucci12-82': 'Gucci',
    'Gucci/gucci2-123': 'Gucci',
    'Gucci/gucci3-62': 'Gucci',
    'Gucci/gucci4-131': 'Gucci',
    'Gucci/gucci5-212': 'Gucci',
    'Gucci/gucci5': 'Gucci',
    'Gucci/gucci8-118': 'Gucci',
    'gucci/gucci8': 'Gucci',
    'guess/guess1-158': 'Guess',
    'guess/guess2-109': 'Guess',
    'guess/guess3-265': 'Guess',
    'guess/guess4-300': 'Guess',
    'guess/guess5-211': 'Guess',
    'GUND/GUND1': 'Gund',
    'Gym Aesthetics/Gym Aesthetics1': 'Gym Aesthetics',
    'HAMANN/HAMANN1': 'Hamann',
    'harley-davidson/harley-davidson2-167': 'Harley-Davidson',
    'harley-davidson/harley-davidson3': 'Harley-Davidson',
    'harley-davidson/harley-davidson4-221': 'Harley-Davidson',
    'harley_owners_group/harley_owners_group1': 'Harley Owners Group',
    'hedbanz/Hedbanz1': 'Hedbanz',
    'hello_kitty/hello_kitty1': 'Hello Kitty',
    'hello_kitty/hello_kitty2-145': 'Hello Kitty',
    'hermes/hermes1-76': 'Hermes',
    'hermes/hermes2-257': 'Hermes',
    'hermes/hermes6': 'Hermes',
    'hermes/hermes6-102': 'Hermes',
    'Hermes/Hermes1': 'Hermes',
    'Hermes/Hermes6': 'Hermes',
    'Hermes/Hermes2': 'Hermes',
    'Hermes/Hermes8': 'Hermes',
    'hermes/hermes8-260': 'Hermes',
    'HERSCHEL/HERSCHEL1': 'Herschel',
    'HOT WHEELS/HOT WHEELS1': 'Hot Wheels',
    'HOUSTON TEXANS/HOUSTON TEXANS1': 'Houston Texans',
    'Hublot/Hublot1-61': 'Hublot',
    'hublot/Hublot1-61': 'Hublot',
    'hublot/Hublot2-205': 'Hublot',
    'Hublot/Hublot2-205': 'Hublot',
    'hugo_boss/hugo_boss5': 'Hugo Boss',
    'hummel/Hummel1': 'Hummel',
    'hummel/hummel1': 'Hummel',
    'INDIANAPOLIS COLTS/INDIANAPOLIS COLTS1': 'Indianapolis Colts',
    'Infiniti/Infiniti1': 'Infiniti',
    'Iron_fist/Iron fist1': 'Iron Fist',
    'Iron_fist1': 'Iron Fist',
    'iron_maiden/iron_maiden1-194': 'Iron Maiden',
    'iron_maiden/iron_maiden2': 'Iron Maiden',
    'iron_maiden/iron_maiden3-283': 'Iron Maiden',
    'isdera/isdera1': 'Isdera',
    'Issey_Miyake/Issey_Miyake1': 'Issey Miyake',
    'Issey_Miyake/Issey_Miyake2': 'Issey Miyake',
    'Issey_Miyake/Issey_Miyake3-214': 'Issey Miyake',
    'IWC/IWC01': 'Iwc',
    'JACK WOLFSKIN/JACK WOLFSKIN1': 'Jack Wolfskin',
    'JACK WOLFSKIN/JACK WOLFSKIN1': 'Jack Wolfskin',
    'JACK WOLFSKIN/JACK WOLFSKIN2': 'Jack Wolfskin',
    'JACK WOLFSKIN/JACK WOLFSKIN2': 'Jack Wolfskin',
    'JACK WOLFSKIN/JACK WOLFSKIN3': 'Jack Wolfskin',
    'JACKSONVILLE JAGUARS/JACKSONVILLE JAGUARS1': 'Jacksonville Jaguars',
    'JURASSIC WORLD/JURASSIC WORLD1': 'Jurassic World',
    'JUUL/JUUL1（打标后待评测）': 'Juul',
    'JUUL/JUUL1': 'Juul',
    'KANSAS CITY CHIEFS/KANSAS CITY CHIEFS1': 'Kansas City Chiefs',
    'kate_spade/kate_spade1': 'Kate Spade',
    'kate_spade1': 'Kate Spade',
    'KENZO/KENZO7': 'Kenzo',
    'KENZO/KENZO1': 'Kenzo',
    'KENZO/kenzo4-275': 'Kenzo',
    'KENZO/KENZO4': 'Kenzo',
    'KENZO/kenzo7-266': 'Kenzo',
    'kiel_james_patrick/kiel_james_patrick1-128': 'Kiel James Patrick',
    'kiel_james_patrick/kiel_james_patrick2-254': 'Kiel James Patrick',
    'Kiel_James_Patrick/Kiel_James_Patrick1': 'Kiel James Patrick',
    'KIPLING/KIPLING1-231': 'Kipling',
    'KIPLING/KIPLING2-169': 'Kipling',
    'KIPLING/KIPLING3-289': 'Kipling',
    'kiss_catalog/kiss_catalog1': 'Kiss Catalog',
    'KLATTERMUSEN/KLATTERMUSEN1': 'Klattermusen',
    'KLATTERMUSEN/KLATTERMUSEN2': 'Klattermusen',
    'KLATTERMUSEN1/KLATTERMUSEN1-44': 'Klattermusen',
    'KLATTERMUSEN1/KLATTERMUSEN2-193': 'Klattermusen',
    'klipsch/klipsch1-118': 'Klipsch',
    'klipsch/klipsch2-173': 'Klipsch',
    'klipsch/klipsch3-194': 'Klipsch',
    'kobe/kobe1': 'Kobe',
    'KontrolFreeka/KontrolFreek1': 'Kontrolfreek',
    'KontrolFreek/KontrolFreek1': 'Kontrolfreek',
    'KYLIE/KYLIE1': 'Kylie',
    'KYLIE/KYLIE2': 'Kylie',
    'KYLIE/KYLIE3': 'Kylie',
    'LAFUMA/LAFUMA1': 'Lafuma',
    'Lancel/Lancel1': 'Lancel',
    'Lancel/Lancel2': 'Lancel',
    'Lancel/Lancel3': 'Lancel',
    'Lanvin/Lanvin2-202': 'Lanvin',
    'lenscrafters/lenscrafters1': 'Lenscrafters',
    'levis/levis11': 'Levis',
    'levis/levis2': 'Levis',
    'levis/levis6': 'Levis',
    'LOS ANGELES CHARGERS/LOS ANGELES CHARGERS1': 'Los Angeles Chargers',
    'LOS ANGELES DODGERS/LOS ANGELES DODGERS1': 'Los Angeles Dodgers',
    'LOS ANGELES DODGERS': 'Los Angeles Dodgers',
    'LOS ANGELES LAKERS/LOS ANGELES LAKERS1': 'Los Angeles Lakers',
    'LOS ANGELES RAMS/LOS ANGELES RAMS1': 'Los Angeles Rams',
    'LOS ANGELES RAMS/LOS ANGELES RAMS2': 'Los Angeles Rams',
    'louis_vuitton/louis_vuitton1-179': 'Louis Vuitton',
    'louis_vuitton/louis_vuitton2-137': 'Louis Vuitton',
    'louis_vuitton/louis_vuitton3-187': 'Louis Vuitton',
    'lululemon/lululemon1-237': 'Lululemon',
    'lululemon/lululemon2-114': 'Lululemon',
    'Luxottica/Luxottica2': 'Luxottica',
    'mammut/mammut1': 'Mammut',
    'mammut/mammut2': 'Mammut',
    'MARMOT/MARMOT1': 'Marmot',
    'Martin Margiela/Martin Margiela1': 'Martin Margiela',
    'marvel/marvel1-108': 'Marvel',
    'marvel/marvel2': 'Marvel',
    'MCILHENNY CO. TABASCO PEPPER SAUCE/MCILHENNY CO. TABASCO PEPPER SAUCE1': 'Tabasco Pepper Sauce',
    'MCILHENNY CO. TABASCO PEPPER SAUCE': 'Tabasco Pepper Sauce',
    'Metallica/Metallica1': 'Metallica',
    'Metallica0/Metallica01': 'Metallica',
    'Metallica/Metallica01': 'Metallica',
    'Metallica/Metallica2': 'Metallica',
    'Metallica/Metallica02': 'Metallica',
    'MIAMI DOLPHINS/MIAMI DOLPHINS1': 'Miami Dolphins',
    'MIAMI DOLPHINS/MIAMI DOLPHINS1w': 'Miami Dolphins',
    'MIAMI DOLPHINS/MIAMI DOLPHINS2': 'Miami Dolphins',
    'MIAMI HEAT/MIAMI HEAT1': 'Miami Heat',
    'Mickey_Mouse/Mickey_Mouse1': 'Mickey Mouse',
    'MINI/MINI1': 'Mini',
    'MINNESOTA VIKINGS/MINNESOTA VIKINGS1': 'Minnesota Vikings',
    'miu_miu/miu_miu1': 'Miu Miu',
    'MONCHHICHI/MONCHHICHI1': 'Monchhichi',
    'MONSTER HIGH/MONSTER HIGH1': 'Monster High',
    'Mont_blanc/Mont_blanc1-111': 'Mont Blanc',
    'Mont_blanc/Mont_blanc2-118': 'Mont Blanc',
    'Mont_blanc/Mont_blanc3-114': 'Mont Blanc',
    'MOTORHEAD/MOTORHEAD1': 'Motorhead',
    'mountain hardwear/mountain hardwear1': 'Mountain Hardwear',
    'mountain hardwear/mountain hardwear2': 'Mountain Hardwear',
    'mozo/mozo1': 'Mozo',
    'NERF/NERF1': 'Nerf',
    'NEW ENGLAND PATRIOTS/NEW ENGLAND PATRIOTS1': 'New England Patriots',
    'NEW ENGLAND PATRIOTS1': 'New England Patriots',
    'NEW ENGLAND PATRIOTS/NEW ENGLAND PATRIOTS2': 'New England Patriots',
    'NEW ORLEANS SAINTS/NEW ORLEANS SAINTS1': 'New Orleans Saints',
    'NEW YORK GIANTS/NEW YORK GIANTS1': 'New York Giants',
    'NEW YORK GIANTS/NEW YORK GIANTS1w': 'New York Giants',
    'NEW YORK GIANTS1': 'New York Giants',
    'NEW YORK GIANTS1w': 'New York Giants',
    'NEW YORK JETS/NEW YORK GIANTS1': 'New York Jets',
    'NEW YORK KNICKS/NEW YORK KNICKS1': 'New York Knicks',
    'NEW YORK KNICKS1': 'New York Knicks',
    'new_balance/new_balance1-186': 'New Balance',
    'new_balance/new_balance2-71': 'New Balance',
    'new_balance/new_balance3-202': 'New Balance',
    'new_york_yankees/new_york_yankees1-183': 'New York Yankees',
    'new_york_yankees/new_york_yankees2-178': 'New York Yankees',
    'NFL/NFL1': 'NFL',
    'niessing/niessing1': 'Niessing',
    'nike/nike1': 'Nike',
    'nike/nike10-294': 'Nike',
    'nike/nike14-207': 'Nike',
    'nike/nike15-294': 'Nike',
    'nike/nike15': 'Nike',
    'nike/nike17-295': 'Nike',
    'nike/nike2-112': 'Nike',
    'nike/nike3-120': 'Nike',
    'nike/nike4-294': 'Nike',
    'nike/nike5-294-207': 'Nike',
    'nike/nike5': 'Nike',
    'nike/nike7-295': 'Nike',
    'nike/nike8-294': 'Nike',
    'nintendo/nintendo2-112': 'Nintendo',
    'Nobis/Nobis1': 'Nobis',
    'Norrona/Norrona1': 'Norrona',
    'OAKLAND RAIDERS/OAKLAND RAIDERS1': 'Oakland Raiders',
    'oakley/oakley1-184': 'Oakley',
    'oakley/oakley2-166': 'Oakley',
    'oakley/oakley3-212': 'Oakley',
    'OCTONAUTS/OCTONAUTS1': 'Octonauts',
    'oliver_peoples/oliver_peoples1': 'Oliver Peoples',
    'oliver_peoples/oliver_peoples2': 'Oliver Peoples',
    'opening_ceremony/opening_ceremony1': 'Opening Ceremony',
    'OtterBOX/OtterBOX1-73': 'Otterbox',
    'OtterBOX/OtterBOX2-155': 'Otterbox',
    'Pandora/Pandora1': 'Pandora',
    'Pandora/Pandora2-210': 'Pandora',
    'panerai/Panerai1': 'Panerai',
    'Panoz/Panoz1': 'Panoz',
    'Paramount/Paramount1': 'Paramount',
    'PATAGONIA/PATAGONIA1-190': 'Patagonia',
    'PATAGONIA/PATAGONIA2-300': 'Patagonia',
    'PATAGONIA/PATAGONIA3-300': 'Patagonia',
    'PATAGONIA/PATAGONIA4-300': 'Patagonia',
    'PATAGONIA/PATAGONIA5': 'Patagonia',
    'patek philippe/patek philippe1': 'Patek Philippe',
    'patek philippe/patek philippe2': 'Patek Philippe',
    'Paul Smith/Paul Smith1': 'Paul Smith',
    'paul_frank/paul_frank1-274': 'Paul Frank',
    'paul_frank/paul_frank2-144': 'Paul Frank',
    'paw_patrol/paw_patrol1': 'Paw Patrol',
    'peppa_pig/peppa_pig1-147': 'Peppa Pig',
    'peppa_pig/peppa_pig2-244': 'Peppa Pig',
    'Persol/Persol1': 'Persol',
    'PETS_ROCK/PETS_ROCK1': 'Pets Rock',
    'PHILADELPHIA EAGLES/PHILADELPHIA EAGLES1': 'Philadelphia Eagles',
    'Philipp Plein/Philipp Plein1': 'Philipp Plein',
    'phlat_ball/phlat_ball1': 'Phlat Ball',
    'piaget/piaget1': 'Piaget',
    'PINK FLOYD/PINK FLOYD1': 'Pink Floyd',
    'PISKE & USAGI/PISKE & USAGI1': 'Piske & Usagi',
    'PITTSBURGH STEELERS/PITTSBURGH STEELERS1': 'Pittsburgh Steelers',
    'piyo/piyo1': 'Piyo',
    'Poetic/Poetic1': 'Poetic',
    'Pokemon/Pokemon1': 'Pokemon',
    'POLLY POCKET/POLLY POCKET1': 'Polly Pocket',
    'pony/pony1': 'Pony',
    'PopSockets/PopSockets2-300': 'Popsockets',
    'PopSockets/PopSockets1': 'Popsockets',
    'popsockets/popsockets1': 'Popsockets',
    'porsche/porsche1': 'Porsche',
    'POWER WHEELS/POWER WHEELS1': 'Power Wheels',
    'prada/prada1-148': 'Prada',
    'prada/prada2-300': 'Prada',
    'prada/prada3-300': 'Prada',
    'prada/prada4-300差170': 'Prada',
    'prada/prada4': 'Prada',
    'prada/prada5-300': 'Prada',
    'prada/prada6-300': 'Prada',
    'Pringle of Scotland/Pringle of Scotland1': 'Pringle Of Scotland',
    'puma/puma1-149': 'Puma',
    'puma/puma2-202': 'Puma',
    'puma/puma3-141': 'Puma',
    'Purdey/Purdey1': 'Purdey',
    'Purdey/Purdey': 'Purdey',
    'quattro/Quattro1': 'Quattro',
    'rainbow_loom/RAINBOW_LOOM1': 'Rainbow Loom',
    'ralph_lauren/ralph_lauren2': 'Ralph Lauren',
    'Ray-Ban/Ray-Ban1': 'Ray-Ban',
    'RAZORBACKS/RAZORBACKS1': 'Razorbacks',
    'RAZORBACKS/RAZORBACKS2': 'Razorbacks',
    'REBEL8/REBEL81': 'Rebel8',
    'REBEL8-184/REBEL81': 'Rebel8',
    'redbull/redbull1': 'Redbull',
    'Replay/Replay2-300': 'Replay',
    'REVLON/REVLON1': 'Revlon',
    'REVLON/REVLON2': 'Revlon',
    'REVLON/REVLON3-300': 'Revlon',
    'roberto_cavalli/ROBERTO_CAVALLI1': 'Roberto Cavalli',
    "rockin'_body/rockin'_body1": "Rockin' Body",
    'rolls-royce/Rolls-Royce1': 'Rolls-Royce',
    'Rossion/Rossion1': 'Rossion',
    'Saleen/Saleen1-300': 'Saleen',
    'Saleen/Saleen1.': 'Saleen',
    'Saleen/Saleen2-157补': 'Saleen',
    'Saleen/Saleen2': 'Saleen',
    'Salewa/Salewa1': 'Salewa',
    'Salewa/Salewa2': 'Salewa',
    'Salewa/Salewa3': 'Salewa',
    'Salomon/Salomon3': 'Salomon',
    'Salvatore Ferragamo/Salvatore Ferragamo1': 'Salvatore Ferragamo',
    'Salvatore Ferragamo/Salvatore Ferragamo2': 'Salvatore Ferragamo',
    'Salvatore Ferragamo/Salvatore Ferragamo6': 'Salvatore Ferragamo',
    'samsung/samsung1': 'Samsung',
    'SAMSUNG1': 'Samsung',
    'SAN FRANCISCO 49ERS/SAN FRANCISCO 49ERS1': 'San Francisco 49Ers',
    'Sandisk/Sandisk1': 'Sandisk',
    'SEATTLE SEAHAWKS/SEATTLE SEAHAWKS1': 'Seattle Seahawks',
    'SENNHEISER/SENNHEISER1': 'Sennheiser',
    'Shelby/Shelby1': 'Shelby',
    'shopkins/shopkins1': 'Shopkins',
    'Shure/Shure1': 'Shure',
    'simply_straight/simply_straight1': 'Simply Straight',
    'Slim_in_6/Slim_in_61': 'Slim In 6',
    'Slim_in/Slim_in_6': 'Slim In 6',
    'smurf/SMURF1': 'Smurf',
    'smurfette/SMURFETTE1': 'Smurfette',
    'snow_white/snow_white1': 'Snow White',
    'Snuggie/Snuggie1': 'Snuggie',
    'Sony_Pictures/Sony_Pictures': 'Sony',
    'Sony_Pictures/Sony_Pictures1': 'Sony',
    'Specialized/Specialized1-103': 'Specialized',
    'Specialized/Specialized2-300': 'Specialized',
    'SPRITE/SPRITE1': 'Sprite',
    'SPRITE/SPRITE2': 'Sprite',
    'stanley/stanley1': 'Stanley',
    'star wars/star wars1': 'Star Wars',
    'Stormtrooper/Stormtrooper1': 'Stormtrooper',
    'STRONG LIFT WEAR/STRONG LIFT WEAR1': 'Strong Lift Wear',
    'subaru/subaru1': 'Subaru',
    'Superman/Superman1': 'Superman',
    'super_mario/Super Mario1': 'Super Mario',
    'supreme/supreme1-180': 'Supreme',
    'supreme/supreme2-114': 'Supreme',
    'Swarovski/Swarovski1-176': 'Swarovski',
    'Swarovski/Swarovski2-241': 'Swarovski',
    'tag_heuer/tag_heuer2-81': 'Tag Heuer',
    'tai_cheng/tai_cheng1': 'Tai Cheng',
    'Talking Tom/Talking Tom 1': 'Talking Tom',
    'Talking Tom/Talking Tom1': 'Talking Tom',
    'TAMIYA/TAMIYA1': 'Tamiya',
    'TAMPA BAY BUCCANEERS/TAMPA BAY BUCCANEERS1': 'Tampa Bay Buccaneers',
    'TAMPA BAY BUCCANEERS/TAMPA BAY BUCCANEERS2': 'Tampa Bay Buccaneers',
    'Tangel/TANGLE1': 'Tangle',
    'TANGLE/TANGLE1': 'Tangle',
    'TENNESSEE TITANS/TENNESSEE TITANS1': 'Tennessee Titans',
    'Tesla/Tesla1': 'Tesla',
    'The Beatles/The Beatles1': 'The Beatles',
    'The Expendables/The Expendables 1': 'The Expendables',
    'The Expendables/The Expendables1': 'The Expendables',
    'The Hunger Games/The Hunger Games1': 'The Hunger Games',
    'Thom Browne/Thom Browne1': 'Thom Browne',
    'Thom Browne/Thom Browne2': 'Thom Browne',
    'Thomas_and_Friends/Thomas_and_Friends1-248': 'Thomas And Friends',
    'Thomas_and_Friends/Thomas_and_Friends2-286': 'Thomas And Friends',
    'Tiger Woods/Tiger Woods1': 'Tiger Woods',
    'tiger_woods/tiger_woods1': 'Tiger Woods',
    'Timberland/Timberland1': 'Timberland',
    'Tommy Hilfiger/Tommy Hilfiger1-202': 'Tommy Hilfiger',
    'Tommy Hilfiger/Tommy Hilfiger2-153': 'Tommy Hilfiger',
    'Tommy Hilfiger/Tommy Hilfiger3-246': 'Tommy Hilfiger',
    'Tommy Hilfiger/Tommy Hilfiger4-289': 'Tommy Hilfiger',
    'TONKA/TONKA1': 'Tonka',
    'Too Faced/Too Faced1': 'Too Faced',
    'tory_burch/tory_burch1-201': 'Tory Burch',
    'tory_burch/tory_burch2-295': 'Tory Burch',
    'tous/tous1-165': 'Tous',
    'tous/tous2-182': 'Tous',
    'tous/tous3-146': 'Tous',
    'toyota/toyota1': 'Toyota',
    'toyota1': 'Toyota',
    'training_mask/training_mask1-212': 'Training Mask',
    'training_mask/training_mask2-210': 'Training Mask',
    'tresor_paris/tresor_paris1': 'Tresor Paris',
    'tresor_paris/tresor_paris2-264': 'Tresor Paris',
    'true_religion/true_religion1-200': 'True Religion',
    'true_religion/true_religion2-145': 'True Religion',
    'turbofire/turbofire1': 'Turbofire',
    'Tweety/Tweety1': 'Tweety',
    'Ulysse Nardin/Ulysse Nardin1': 'Ulysse Nardin',
    'vans/vans1-75': 'Vans',
    'vans/vans2-172': 'Vans',
    'vans/vans3-198': 'Vans',
    'Van_Cleef/Van_Cleef1': 'Van Cleef',
    'Van_Cleef/Van_Cleef2-276': 'Van Cleef',
    'Van_Cleef/Van_Cleef3-147': 'Van Cleef',
    'VAUDE/VAUDE1': 'Vaude',
    'VAUDE/VAUDE2': 'Vaude',
    'Versace/Versace1-138': 'Versace',
    'Versace/Versace2-143': 'Versace',
    'Versace/Versace3': 'Versace',
    'Versace/Versace4': 'Versace',
    'Versace/Versace5-213': 'Versace',
    'Versace/Versace6-194': 'Versace',
    'Versace/Versace7-300': 'Versace',
    'Versace/Versace': 'Versace',
    'VEUVE AMBAL/VEUVE AMBAL1': 'Veuve Ambal',
    'Vivienne Westwood/Vivienne Westwood1': 'Vivienne Westwood',
    'VOLCOM/VOLCOM1': 'Volcom',
    'Volvo/Volvo1': 'Volvo',
    #     'Walt_Disney/Walt_disney1': 'Walt Disney',
    #     'Walt_disney/Walt_disney1': 'Walt Disney',
    #     'Walt_disney/Walt_disney10': 'Walt Disney',
    #     'Walt_Disney/Walt_disney10': 'Walt Disney',
    #     'Walt_Disney/Walt_disney11': 'Walt Disney',
    #     'Walt_Disney/Walt_disney15': 'Walt Disney',
    #     'Walt_Disney/Walt_disney17': 'Walt Disney',
    #     'Walt_disney/Walt_disney17': 'Walt Disney',
    #     'Walt_disney/Walt_disney18': 'Walt Disney',
    #     'Walt_Disney/Walt_disney18': 'Walt Disney',
    #     'Walt_Disney/Walt_disney19': 'Walt Disney',
    #     'Walt_Disney/Walt_disney2': 'Walt Disney',
    #     'Walt_Disney/Walt_disney20': 'Walt Disney',
    #     'Walt_disney/Walt_disney20': 'Walt Disney',
    #     'Walt_Disney/Walt_disney21': 'Walt Disney',
    #     'Walt_Disney/Walt_disney22': 'Walt Disney',
    #     'Walt_Disney/Walt_disney23': 'Walt Disney',
    #     'Walt_disney/Walt_disney23': 'Walt Disney',
    #     'Walt_Disney/Walt_disney24': 'Walt Disney',
    #     'Walt_disney/Walt_disney24': 'Walt Disney',
    #     'Walt_Disney/Walt_disney25': 'Walt Disney',
    #     'Walt_disney/Walt_disney25': 'Walt Disney',

    'Walt_disney/Walt_disney1': 'Disnet',
    'Walt_disney/Walt_disney10': 'Dumbo',
    'Walt_disney/Walt_disney11': 'Piglet',
    'Walt_disney/Walt_disney15': 'Disnet Planes',
    'Walt_disney/Walt_disney17': 'Princess Magnet',
    'Walt_disney/Walt_disney18': 'Mr. Incredible',
    'Walt_disney/Walt_disney19': 'Goofy',
    'Walt_disney/Walt_disney20': 'McStuffins',
    'Walt_disney/Walt_disney21': 'Daisy Duck',
    'Walt_disney/Walt_disney23': 'Oswald the Lucky Rabbit',
    'Walt_disney/Walt_disney24': 'Mickey Mouse',
    'Walt_disney/Walt_disney25': 'Minnie Mouse',

    'warner_bros/warner_bros2-169': 'Warner Bros',
    'xtep/xtep1': 'Xtep',
    'Yohji Yamamoto/Yohji Yamamoto1': 'Yohji Yamamoto',
    'Zeiss/Zeiss1': 'Zeiss',
    'LANVIN/LANVIN1': 'LANVIN',
    'LANVIN/LANVIN2': 'LANVIN',
    'APPLE': 'Apple'
}
import re


def remove_trailing_number(s):
    # 使用正则表达式匹配“-数字”结尾的模式
    pattern = re.compile(r'-[0-9]+$')
    # 如果匹配，则去除该部分
    if pattern.search(s):
        return pattern.sub('', s)
    else:
        return s


logo2brand = {}
for key, value in logo2brand_org.items():
    new_key = remove_trailing_number(key)
    logo2brand[key] = value
    logo2brand[key.lower()] = value
    logo2brand[key.upper()] = value
    logo2brand[new_key] = value
    logo2brand[new_key.replace('_', ' ')] = value
    logo2brand[key.replace('Walt_Disney', 'Walt_disney')] = value
    logo2brand[key.title()] = value
    logo2brand[key.split('/')[-1]] = value

sample_logo = [
    'Agnes_b/Agnes_b1',
    'Aston_Martin/Aston_Martin1',
    'Boy_London/Boy_London1',
    'burberry/burberry1',
    'burberry/burberry2',
    'Cartier/Cartier3',
    'Estee_Lauder/Estee_Lauder2',
    'hello_kitty/hello_kitty1',
    'Issey_Miyake/Issey_Miyake2',
    'KYLIE/KYLIE3',
    'Mickey_Mouse/Mickey_Mouse1',
    'nike/nike1',
    'Pokemon/Pokemon1',
    'SENNHEISER/SENNHEISER1',
    'snow_white/snow_white1',
    'tresor_paris/tresor_paris1',
    'Versace/Versace3',
    'Versace/Versace4',
    'xtep/xtep1',
    'bally/bally1'
]
# 训练集2添加的类别
sample_logo2 = [
    'TENNESSEE TITANS/TENNESSEE TITANS1',
    'chrome_hearts/chrome_hearts2',
    'Dior/Dior1',
    'POWER WHEELS/POWER WHEELS1',
    'Thom Browne/Thom Browne1',
    'The Hunger Games/The Hunger Games1',
    'FIREMAN SAM/FIREMAN SAM1',
    'bostitch/bostitch1',
    'Philipp Plein/Philipp Plein1',
    'levis/levis2',
    'conair/conair1',
    'Van_Cleef/Van_Cleef1',
    'LOS ANGELES CHARGERS/LOS ANGELES CHARGERS1',
    'piaget/piaget1',
    'Volvo/Volvo1',
    'David_Yurman/David Yurman2',
    'AQUABEADS/AQUABEADS1',
    'fox/fox2',
    'subaru/subaru1',
    'toyota/toyota1'
]

test_logo = ['new_balance/new_balance1-186',
             'hermes/hermes6-102',
             'puma/puma3-141',
             'Comme Des Garcons/Comme Des Garcons1',
             'Metallica/Metallica1',
             'FISHER-PRICE/FISHER-PRICE1',
             'lululemon/lululemon1-237',
             'Mont_blanc/Mont_blanc1-111',
             'Walt_Disney/Walt_disney15',
             'ARIZONA CARDINALS/ARIZONA CARDINALS1',
             'REVLON/REVLON2',
             'smurf/SMURF1',
             'OAKLAND RAIDERS/OAKLAND RAIDERS1',
             'Tesla/Tesla1',
             'dc_shoes/DC_Shoes1',
             'Estee_Lauder/Estee_Lauder4-300',
             'puma/puma1-149',
             'Dior/dior2-110',
             'BUFFALO BILLS/BUFFALO BILLS1',
             'LOS ANGELES LAKERS/LOS ANGELES LAKERS1']

test_logo1 = [  # 4+6+1+2+3+1+2
    # 运动休闲品牌
    'new_balance/new_balance1-186',
    'puma/puma1-149',
    'vans/vans1-75',  # 文字
    'vans/vans2-172',

    # 奢侈品牌（包、衣服）
    'lululemon/lululemon1-237',
    'hermes/hermes1-76',
    'Dior/dior2-110',
    'Mont_blanc/Mont_blanc1-111',
    'Estee_Lauder/Estee_Lauder2',
    'burberry/burberry3-97',  # 风格
    'DKNY/DKNY3',

    # 表
    'piaget/piaget1',

    # 车
    'Tesla/Tesla1',
    'Volvo/Volvo1',

    # 动漫人物
    'Walt_Disney/Walt_disney22',  # 唐老鸭
    'peppa_pig/peppa_pig1-147',
    'super_mario/Super Mario1',

    # 快消品
    'redbull/redbull1',

    # 电子产品
    'bose/bose1',
    'Sandisk/Sandisk1',
]