logo2brand = {
    'Agnes b/Agnes b1': 'Agnes b',
    'Agnes_b/Agnes_b1': 'Agnes b',
    'Agnes_b/Agnes_b2': 'Agnes b',
    'Agnes_b/Agnes_b3': 'Agnes b',
    'Agnes_b/Agnes_b4': 'Agnes b',
    'Aston_Martin/Aston_Martin1': 'Aston Martin',
    'Boy_London/Boy_London1': 'Boy London',
    'Boy_London/Boy_London2': 'Boy London',
    'burberry/burberry1': 'Burberry',
    'burberry/burberry2': 'Burberry',
    'Burberry/Burberry1': 'Burberry',
    'Burberry/Burberry2': 'Burberry',
    'Burberry/Burberry3': 'Burberry',
    'Cartier/Cartier3': 'Cartier',
    'cartier/cartier1': 'Cartier',
    'cartier/cartier3': 'Cartier',
    'Estee_Lauder/Estee_Lauder2': 'Estee Lauder',
    'Estee Lauder/Estee Lauder1': 'Estee Lauder',
    'Estee Lauder/Estee Lauder2': 'Estee Lauder',
    'hello_kitty/hello_kitty1': 'Hello Kitty',
    'hello_kitty/hello_kitty2': 'Hello Kitty',
    'Issey_Miyake/Issey_Miyake2': 'Issey Miyake',
    'KYLIE/KYLIE1': 'KYLIE',
    'KYLIE/KYLIE2': 'KYLIE',
    'KYLIE/KYLIE3': 'KYLIE',
    'Mickey_Mouse/Mickey_Mouse1': 'Mickey Mouse',
    'nike/nike1': 'Nike',
    'nike/nike2': 'Nike',
    'nike/nike5': 'Nike',
    'nike/nike15': 'Nike',
    'Pokemon/Pokemon1': 'Pokemon',
    'SENNHEISER/SENNHEISER1': 'Sennheiser',
    'snow_white/snow_white1': 'Snow White',
    'tresor_paris/tresor_paris1': 'Tresor Paris',
    'tresor_paris/tresor_paris2': 'Tresor Paris',
    'Versace/Versace1': 'Versace',
    'Versace/Versace2': 'Versace',
    'Versace/Versace3': 'Versace',
    'Versace/Versace4': 'Versace',
    'Versace/Versace7': 'Versace',
    'xtep/xtep1': 'Xtep',
    'bally/bally1': 'Bally',
    'TENNESSEE TITANS/TENNESSEE TITANS1': 'Tennessee Titans',
    'chrome_hearts/chrome_hearts2': 'Chrome Hearts',
    'chrome_hearts/chrome_hearts4': 'Chrome Hearts',
    'chrome_hearts/chrome_hearts5': 'Chrome Hearts',
    'Dior/Dior1': 'Dior',
    'Dior/Dior2': 'Dior',
    'POWER WHEELS/POWER WHEELS1': 'Power Wheels',
    'Thom Browne/Thom Browne1': 'Thom Browne',
    'Thom Browne/Thom Browne2': 'Thom Browne',
    'The Hunger Games/The Hunger Games1': 'The Hunger Games',
    'FIREMAN SAM/FIREMAN SAM1': 'Fireman Sam',
    'bostitch/bostitch1': 'Bostitch',
    'Philipp Plein/Philipp Plein1': 'Philipp Plein',
    'levis/levis2': 'Levis',
    'levis/levis6': 'Levis',
    'levis/levis11': 'Levis',
    'conair/conair1': 'Conair',
    'Conair/Conair1': 'Conair',
    'Van_Cleef/Van_Cleef1': 'Van Cleef',
    'Van_Cleef/Van_Cleef2': 'Van Cleef',
    'Van_Cleef/Van_Cleef3': 'Van Cleef',
    'LOS ANGELES CHARGERS/LOS ANGELES CHARGERS1': 'Los Angeles Chargers',
    'piaget/piaget1': 'Piaget',
    'Volvo/Volvo1': 'Volvo',
    'VOLCOM/VOLCOM1': 'Volvo',
    'David_Yurman/David_Yurman1': 'David Yurman',
    'David_Yurman/David Yurman2': 'David Yurman',
    'David_Yurman/David_Yurman2': 'David Yurman',
    'AQUABEADS/AQUABEADS1': 'Aquabeads',
    'fox/fox1': 'Fox',
    'fox/fox2': 'Fox',
    'subaru/subaru1': 'Subaru',
    'subaru1': 'Subaru',
    'toyota/toyota1': 'Toyota',
    'toyota1': 'Toyota'
}

sample_logo = [
    'Agnes_b/Agnes_b1',
    'Aston_Martin/Aston_Martin1',
    'Boy_London/Boy_London1',
    'burberry/burberry1',
    'burberry/burberry2',
    'Cartier/Cartier3',
    'Estee_Lauder/Estee_Lauder2',
    'hello_kitty/hello_kitty1',
    'Issey_Miyake/Issey_Miyake2',
    'KYLIE/KYLIE3',
    'Mickey_Mouse/Mickey_Mouse1',
    'nike/nike1',
    'Pokemon/Pokemon1',
    'SENNHEISER/SENNHEISER1',
    'snow_white/snow_white1',
    'tresor_paris/tresor_paris1',
    'Versace/Versace3',
    'Versace/Versace4',
    'xtep/xtep1',
    'bally/bally1'
]
# 训练集2添加的类别
sample_logo2 = [
    'TENNESSEE TITANS/TENNESSEE TITANS1',
    'chrome_hearts/chrome_hearts2',
    'Dior/Dior1',
    'POWER WHEELS/POWER WHEELS1',
    'Thom Browne/Thom Browne1',
    'The Hunger Games/The Hunger Games1',
    'FIREMAN SAM/FIREMAN SAM1',
    'bostitch/bostitch1',
    'Philipp Plein/Philipp Plein1',
    'levis/levis2',
    'conair/conair1',
    'Van_Cleef/Van_Cleef1',
    'LOS ANGELES CHARGERS/LOS ANGELES CHARGERS1',
    'piaget/piaget1',
    'Volvo/Volvo1',
    'David_Yurman/David Yurman2',
    'AQUABEADS/AQUABEADS1',
    'fox/fox2',
    'subaru/subaru1',
    'toyota/toyota1'
]

# test_logo = [
#     'new_balance/new_balance1-186',
#     'hermes/hermes6-102',
#     'puma/puma3-141',
#     'Comme Des Garcons/Comme Des Garcons1',
#     'Metallica/Metallica1',
#     'FISHER-PRICE/FISHER-PRICE1',
#     'lululemon/lululemon1-237',
#     'Mont_blanc/Mont_blanc1-111',
#     'Walt_Disney/Walt_disney15',
#     'ARIZONA CARDINALS/ARIZONA CARDINALS1',
#     'REVLON/REVLON2',
#     'smurf/SMURF1',
#     'OAKLAND RAIDERS/OAKLAND RAIDERS1',
#     'Tesla/Tesla1',
#     'dc_shoes/DC_Shoes1',
#     'redbull/redbull1',
#     # 'Estee_Lauder/Estee_Lauder4-300',
#     'puma/puma1-149',
#     # 'Dior/dior2-110',
#     'BUFFALO BILLS/BUFFALO BILLS1',
#     'LOS ANGELES LAKERS/LOS ANGELES LAKERS1']

test_logo = test_logo1 = [  # 4+6+1+2+3+1+2
    # 运动休闲品牌
    'new_balance/new_balance1-186',
    'puma/puma1-149',
    'vans/vans1-75',  # 文字
    'vans/vans2-172',

    # 奢侈品牌（包、衣服）
    'lululemon/lululemon1-237',
    'hermes/hermes1-76',
    'Dior/dior2-110',
    'Mont_blanc/Mont_blanc1-111',
    'Estee_Lauder/Estee_Lauder2',
    'burberry/burberry3-97',  # 风格
    'DKNY/DKNY3',

    # 表
    'piaget/piaget1',

    # 车
    'Tesla/Tesla1',
    'Volvo/Volvo1',

    # 动漫人物
    'Walt_Disney/Walt_disney22',  # 唐老鸭
    'peppa_pig/peppa_pig1-147',
    'super_mario/Super Mario1',

    # 快消品
    'redbull/redbull1',

    # 电子产品
    'bose/bose1',
    'Sandisk/Sandisk1',
]


brand_link = {
    'waltdisney': ['donald', 'donaldduck'],
    'supermario': ['mario'],
}


none_brand_label_org = {
    '31eSNcWV-yL.jpg': 'Kingston',
    '31gQkUJbTDL.jpg': 'Logitech',
    '41+zRFPNapL.jpg': 'Sony',
    '412x5cdITfL.jpg': 'Canon',
    '413F8m5Xb2L.jpg': 'Kingston',
    '414BrTe0qhL.jpg': 'JBL',
    '415DW88RT5L.jpg': 'Samsung.',
    '415jm2nCG7L.jpg': 'CORSAIR',
    '415mQZxocHL.jpg': 'Minion',
    '4183KdOQ-5L.jpg': 'Bvlgari.',
    '41dAN10tIFS.jpg': 'AMD, Nvidia',
    '41dlmN6rWoL._AC_.jpg': 'HP',
    '41FMfUKWnoL.jpg': 'Tweety.',
    '41GZXRDATFL.jpg': 'Balenciaga.',
    '41HhAlthPhL.jpg': 'Chanel.',
    '41JecjzxdWL.jpg': 'Kingston',
    '41JfTUbhwYL.jpg': 'Canon',
    '41kGjES4roL.jpg': 'Bvlgari.',
    '41n12aWyN7L.jpg': 'PlayStation.',
    '41S0LzDVcsL.jpg': 'ZOTAC',
    '41S2FGeKU4L.jpg': 'Prada.',
    '41saMQRIdjL.jpg': 'Loreal.',
    '41VAC6LyXBL.jpg': 'Bvlgari.',
    '41Whbq7pKaL.jpg': 'PRADA',
    '41wijeVoiFL.jpg': 'HP.',
    '41WW6I-sw3L.jpg': 'Mont Blanc.',
    '41x28nGFvML.jpg': 'Avene',
    '41y04zfLf2L.jpg': 'Under Armour.',
    '41Za9Jsx5iL._AC_.jpg': 'Peanuts, Snoopy',
    '41Zolz9B+rL.jpg': 'Kingston',
    '41ZTPQ5I+QL.jpg': 'Sony.',
    '5107calipGL.jpg': 'topps',
    '511FBm4x1yL.jpg': 'Under Armour, UA',
    '512dflo7gSL._AC_.jpg': 'Canon',
    '51322r5V2kL.jpg': 'Kingston',
    '515T6bl16KL.jpg': 'New England Patriots.',
    '517DGNHCO3L.jpg': 'Longines.',
    '518tbshI3kL.jpg': 'Samsung.',
    '518VafsplzL.jpg': 'Snoopy',
    '51bVipN8CpL.jpg': 'New Balance.',
    '51Ca2XZl6EL.jpg': 'Bvlgari.',
    '51cl5iKGjsL.jpg': 'Chanel.',
    '51EzP7f2A8L.jpg': 'Prada.',
    '51F7DpV4uvL.jpg': 'MOSCHINO',
    '51FBq9G+V7L._AC_.jpg': 'Versace.',
    '51fVIDmuhwL.jpg': 'Oster',
    '51Gguuv3K6L.jpg': 'Garfield.',
    '51GPAUPHUOL.jpg': 'intel',
    '51HhTWrBw6L.jpg': 'Longines.',
    '51HXUj-e8+L.jpg': 'Yves Saint Laurent.',
    '51ie-1lhf3L.jpg': 'Givenchy.',
    '51InTx5t+iL.jpg': 'MLB',
    '51iVvO3D5XL.jpg': 'PHILIPS',
    '51IW4m-Oy0L.jpg': 'MLB',
    '51jWkJbZrTL.jpg': 'Canon',
    '51Kqk+UlzgL.jpg': 'SanDisk',
    '51lOuuwIC1L.jpg': 'Mario.',
    '51lZRJIGs5L.jpg': 'Shelby.',
    '51o2kTtQicL.jpg': 'There are None.',
    '51Par1RXO9L._AC_.jpg': 'Los Angeles Dodgers, MLB.',
    '51qthZ5rc6L.jpg': 'Razer',
    '51RbduTD83L.jpg': 'Hanna Barbera',
    '51RDffu5oyL.jpg': 'Gold S Gym.',
    '51VG6toFXQL.jpg': 'Razer',
    '51WFRJ6Y+QL.jpg': 'Broncos, Xbox',
    '51wJjm-ZpyL.jpg': 'WWE.',
    '51wQ2Fe4nAL._SL1500_.jpg': 'Loreal.',
    '51wS8wER0QL.jpg': 'Puma.',
    '51wtbSrIqGL.jpg': 'New Balance.',
    '51Zd-rRIKcL.jpg': 'Armani.',
    '61+rG6CuguL.jpg': '不知道',
    '610uOfbuCtL.jpg': 'MLB',
    '611NbNctb+L.jpg': 'Super Mario.',
    '61-1pbebnVL.jpg': 'Philips.',
    '612JZgwMLLL.jpg': 'Snoopy',
    '613tX6cMHkL.jpg': 'Minions',
    '614aLZPNNWL.jpg': 'Iron Man',
    '614txof3tWL.jpg': 'CORSAIR',
    '615fimw6rkL.jpg': 'SEAGATE',
    '615p0P2lPLL._AC_SL1000_.jpg': 'Hot Toys.',
    '616PzK-PzwL._AC_UL1000_.jpg': 'Under Armour, UA',
    '6184-4eckiL.jpg': 'Nintendo, Super Mario.',
    '618a9uV2dZL._AC_SL1000_.jpg': 'HP, Xbox',
    '61919P52wfL._AC_SL1221_.jpg': 'Lenovo',
    '619LNf-uCcL.jpg': 'Prada.',
    '619ZT5pLV9L.jpg': 'Peppa Pig.',
    '61C6nr1e3pL._AC_UL1200_.jpg': 'Reebok.',
    '61caftFq8iL._AC_SL1050_.jpg': 'Apple',
    '61c-ssMsIbL.jpg': 'Garfield.',
    '61cUuYfvL8L.jpg': 'NFL, Topps.',
    '61D-hdfgaSL.jpg': 'Guess',
    '61E3OcPkyqL.jpg': 'Mario.',
    '61E8OzcmjhL.jpg': 'DKNY.',
    '61FPK7rXjCL.jpg': 'Garfield.',
    '61fT3bGKQnL.jpg': 'Coach',
    '61FzkIV4jEL.jpg': 'Sandisk',
    '61G9J4VaaPL.jpg': 'Fendi.',
    '61h88KzVMBL.jpg': 'Minions',
    '61I1gOj5szL.jpg': 'Pepsi, Coca Cola',
    '61JJ5o90XdL.jpg': 'Fila.',
    '61m6kgy8ZdL.jpg': 'MLB, topps',
    '61m7JsupfjL.jpg': 'JBL',
    '61mf5bdoxvL.jpg': 'DKNY.',
    '61mgO54QcyL.jpg': 'Fendi.',
    '61MHBSc8IZL.jpg': 'Fila.',
    '61N-mSY2E6L._SL1024_.jpg': 'Disnet, McStuffins.',
    '61OI8tDUt6L.jpg': 'Sandisk',
    '61ps6mluuNL.jpg': 'Garfield.',
    '61px+8YzJ0L._AC_SL1200_.jpg': 'Marvel, Captain America.',
    '61Qh6MKxFbL.jpg': 'New Balance.',
    '61RH26O+iLL.jpg': 'Coach.',
    '61si4koVAbL.jpg': 'skechers',
    '61sP5IDYyAL.jpg': 'Spongebob',
    '61uCjKl9m2L.jpg': 'LACOSTE',
    '61VGXQsNFuL.jpg': 'Vans.',
    '61wBybC4DIL.jpg': 'Minion.',
    '61we5QG1sBL.jpg': 'There are None.',
    '61YewwNYYIL.jpg': 'Tommy Hilfiger.',
    '61yr-Qt-ZJL.jpg': 'Sandisk',
    '61YT2eKwcbL.jpg': 'Nvidia',
    '61zDfSZO6YL.jpg': 'Winnie the Pooh.',
    '61zVoVUZxML.jpg': 'Sandisk',
    '61zwxKC70OL._AC_UL1000_.jpg': 'Under Armour.',
    '71+5nQJ2NoL.jpg': 'Salvatore Ferragamo.',
    '710KViU7FWL.jpg': 'Reebok.',
    '714eLeK9C4L.jpg': 'Philips.',
    '718Cmahc4sL.jpg': 'Apple',
    '718Xdz6W92L.jpg': 'Snoopy',
    '719n6MRJcKL.jpg': 'skechers',
    '71aqB87TbTL.jpg': 'Fila.',
    '71BWRQ6eXtL.jpg': 'Apple.',
    '71CgBsGRf8L.jpg': 'Xbox',
    '71cJ0OgxNWL._AC_UL1500_.jpg': 'arnette',
    '71DDI6PhVrL.jpg': 'Crazy Boxer, Patrick Star',
    '71DSLlmWEcL.jpg': 'Spongebob',
    '71dVrFKFLoL.jpg': 'The North Face',
    '71e92g9XvUL.jpg': 'Puma.',
    '71EigNXT98L.jpg': 'Mario.',
    '71GdSeDeivL._AC_UL1500_.jpg': 'Levis',
    '71ggQCxzAOL.jpg': 'Sandisk',
    '71gWHC1h2cL.jpg': 'ALIENWARE',
    '71gXPh13uvL.jpg': 'Vans.',
    '71gzTDGVKoL.jpg': 'Razer',
    '71H0Ph5e7nL.jpg': 'TOSHIBA',
    '71HEq9s-sNL.jpg': 'Minion',
    '71IhQ6ZG05L.jpg': 'mustela',
    '71Ik8Fh-yHL.jpg': 'Canon',
    '71JeY0XU-IL.jpg': 'Midea',
    '71kQe2Y+MsL.jpg': 'Peppa Pig.',
    '71kT1cvvOoL.jpg': 'Sonic.',
    '71LmYNuhC1L._AC_SL1000_.jpg': 'Chanel, Celine, Samsung',
    '71nP+vzq-iL._AC_UL1500_.jpg': 'Casio.',
    '71nYkK3A5PL.jpg': 'Lacoste.',
    '71OaGr-PIcL.jpg': 'Mont Blanc.',
    '71p3YB0jgOL.jpg': 'LORAC',
    '71p6JTK8RQL.jpg': 'Fila.',
    '71p-A14s4cL.jpg': 'Fendi.',
    '71PCStiVDrL.jpg': 'Lenovo',
    '71R9Xig7TQL._AC_SL1500_.jpg': 'Winnie the Pooh.',
    '71SGV88dhRL._SL1500_.jpg': 'Dove',
    '71sjwwvRqyL.jpg': 'Kingston',
    '71t3sKIg9OL.jpg': 'skechers',
    '71trkDp5ZBL.jpg': 'Lacoste.',
    '71VeUR-GDCL.jpg': 'Fendi.',
    '71vrbzYDfAL.jpg': 'Paw Patrol.',
    '71XgdqMi3QL.jpg': 'PlayStation.',
    '71y02y2RgxL._AC_SL1200_.jpg': '不知道',
    '71Y9L4E+DWL.jpg': 'Nvidia, AMD',
    '71ygubfsr1L.jpg': 'Peppa Pig.',
    '71ZIpoKbMzL.jpg': 'VALENTINO',
    '71ZUuTINBcL.jpg': 'Paw Patrol.',
    '71zvmGGdjML.jpg': 'Michael Kors',
    '71ZZ+tbtVBL.jpg': 'Lacoste.',
    '810RJfn4uKL.jpg': 'Reebok.',
    '811ff4aU1SL.jpg': 'Converse',
    '81346JKfOoL.jpg': 'Garfield.',
    '813SvJ7rxAL.jpg': 'kate spate',
    '814EvHIrrKL.jpg': 'Lacoste.',
    '817dSkcftcL._AC_UL1500_.jpg': 'SALOMON',
    '818IVXlF-YL.jpg': 'Puma.',
    '819s7vgTMXL.jpg': 'Salvatore Ferragamo.',
    '81agj7DGlmL.jpg': 'Puma.',
    '81ANgBvx2uL.jpg': 'Sony.',
    '81arbLuVKAL._AC_UL1500_.jpg': 'Daisy Duck.',
    '81awGxGKIcL.jpg': 'Polo.',
    '81b9NqEKa6L.jpg': 'skechers',
    '81BIHf9g25L.jpg': 'Garfield.',
    '81CqCtSngGL.jpg': 'Tissot.',
    '81-cSO45weL.jpg': 'skechers',
    '81cTJS+DovL.jpg': 'BAUME&MERCIER',
    '81DgCoggktL.jpg': 'LG.',
    '81Dntl6NdEL.jpg': 'SALOMON',
    '81e62Wn03DL._AC_UL1500_.jpg': 'Kansas City Royals.',
    '81ejNrrGn8L.jpg': 'New Balance.',
    '81enQLmb3OL.jpg': 'TOPPS',
    '81FKRExH58L.jpg': 'Hugo Boss.',
    '81GC8lN3cjL.jpg': 'HP.',
    '81GPM5ykywL.jpg': 'NFL',
    '81he3WEFRvL.jpg': '不知道',
    '81hsNlrRRqL.jpg': 'Canon',
    '81hUuesgKfL.jpg': 'Baume & Mercier.',
    '81Ia1roVRcL.jpg': 'Reebok.',
    '81Im4NnJb7L.jpg': 'Guess.',
    '81jgGjTpWnL.jpg': 'Tissot.',
    '81JkxQN6DJL.jpg': 'Tissot.',
    '81K96TZPrwL.jpg': 'Peppa Pig.',
    '81-KL7QNSNL.jpg': 'Salvatore Ferragamo.',
    '81kM7boTnyL.jpg': 'Tag Heuer.',
    '81LH3xL8N0L.jpg': 'SALOMON',
    '81lJh-IL1JL.jpg': 'Asus.',
    '81lN8isMgSL.jpg': 'There are None.',
    '81LthYoRM1L._AC_UL1500_.jpg': 'Under Armour.',
    '81m4pdYytZL.jpg': 'Paw Patrol.',
    '81mY3RBnKsL.jpg': 'Puma.',
    '81ODt1IHSPL.jpg': 'Guess.',
    '81OKQzPu3LL.jpg': 'Calvin Klein.',
    '81OyzXisETL.jpg': 'Paw Patrol.',
    '81Pesex1r7L.jpg': 'Dalmatian.',
    '81pjCPTgY+L.jpg': 'asics',
    '81PuX7UYwPL.jpg': 'Hello Kitty.',
    '81qL2u-yptL.jpg': 'Columbia.',
    '81RCWSYS0kL.jpg': 'DKNY.',
    '81RRt2cikrL.jpg': 'Kingston',
    '81sEHw4vaPL.jpg': 'Puma.',
    '81TQumlpQKL.jpg': 'Garfield.',
    '81V1wX+NfLL.jpg': 'Sonic.',
    '81vBiaoT34L.jpg': 'Paw Patrol.',
    '81WyBGIKSwL.jpg': 'Peppa Pig.',
    '81x+EEzQn2L.jpg': 'Paw Patrol.',
    '81xK22bxBYL.jpg': 'Broncos, NFL, Super Bowl, Nike',
    '81xk5J6HrFL.jpg': 'Chevrolet.',
    '81XKvGMvX-L.jpg': 'Converse',
    '81Z9DRmWgiL.jpg': 'Coach, Snoopy',
    '81ZDhVXp9kL.jpg': 'Peppa Pig.',
    '81zjHr2wjBL._AC_SL1500_.jpg': 'The North Face',
    '81ZwHiKlFcL.jpg': 'Sonic.',
    '911hPU5DcXL.jpg': 'Tissot.',
    '912WOQ2EXPL.jpg': 'Skechers',
    '915X1Jx4HSL._AC_UL1500_.jpg': 'Pittsburgh Steelers.',
    '916CPu+CKUL.jpg': 'Minion',
    '91B2ar+ZJIL.jpg': 'Balenciaga.',
    '91im3IAJhmL.jpg': 'New Balance.',
    '91jwEBrKLRL._AC_UL1500_.jpg': 'Calvin Klein',
    '91kdc4RBDWL.jpg': 'SALOMON',
    '91nm5ksUXuL.jpg': 'Tag Heuer.',
    '91yYuLMPPXL.jpg': 'Coach.',
    '91zWWbkTBDL._AC_UL1500_.jpg': 'Reebok.',
}

none_brand_label = {}
for key, value in none_brand_label_org.items():
    value = value.rstrip('.').replace('_', '').replace(' ', '').lower().replace("'", "").split(',')
    none_brand_label[key] = value